# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 主题 Redefine 配置文件 V2
# 作者：EVANNOTFOUND
# GitHub：https://github.com/EvanNotFound/hexo-theme-redefine
# 文档：https://redefine-docs.ohevan.com
# 演示：https://redefine.ohevan.com
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 基础信息 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/basic/info
info:
  # 站点标题
  title: ALp_Studio Article Library
  # 站点副标题
  subtitle: ReStart Version
  # 作者名称
  author: 亓翎_Re-Tikara
  # 站点 URL
  url: https://RE-TikaRa.github.io
# 基础信息 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 图片配置 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/basic/defaults
defaults:
  # 网站图标（Favicon）
  favicon: https://youke2.picui.cn/s1/2025/12/22/69487018d79ad.ico
  # 站点 Logo
  logo: https://s2.loli.net/2025/12/22/BF6ApZlzjyELX5K.png
  # 站点头像
  avatar: https://s2.loli.net/2025/12/22/mkWtIYraVxdnTCe.jpg
# 图片配置 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 颜色 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/basic/colors
colors:
  # 主色
  primary: "#98B37D"
  # 辅助色（待定）
  secondary: "#997868"
  # 默认主题模式初始值（会被 prefers-color-scheme 覆盖）
  default_mode: light # light（浅色）, dark（深色）
# 颜色 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 站点自定义 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/basic/global
global:
  # 自定义全局字体
  fonts:
    # 中文字体
    chinese: 
      enable: false # 是否启用自定义中文字体
      family:  # 字体族（Font family）
      url:  # 字体 CSS 文件 URL
    # 英文字体
    english: 
      enable: false # 是否启用自定义英文字体
      family:  # 字体族（Font family）
      url:  # 字体 CSS 文件 URL
    # 自定义标题字体（导航栏、侧边栏）
    title:
      enable: false # 是否启用自定义标题字体
      family:  # 字体族（Font family）
      url:  # 字体 CSS 文件 URL
  # 内容最大宽度
  content_max_width: 1000px
  # 侧边栏宽度
  sidebar_width: 210px
  # 鼠标悬停效果
  hover:
    shadow: true # 阴影效果
    scale: true # 缩放效果
  # 滚动进度
  scroll_progress:
    bar: true # 进度条
    percentage: true # 百分比
  # 网站计数器
  website_counter:
    url: https://cn.vercount.one/js # 计数 API URL（一般无需修改）
    enable: true # 是否启用网站计数器
    site_pv: true # 全站浏览量（PV）
    site_uv: true # 全站访客数（UV）
    post_pv: true # 文章浏览量（PV）
  # 是否启用单页体验（使用 swup）。见 https://swup.js.org/ ，类似 pjax
  single_page: true
  # 是否启用预加载动画（Preloader）
  preloader:
    enable: true
    custom_message: 欢迎进入，实验体 # 自定义提示文案；为空则显示站点标题
  # 侧边工具设置
  side_tools:
    # 是否启用设置按钮齿轮旋转动画
    gear_rotation: true
    # 页面加载时是否自动展开工具列表
    auto_expand: true
  # 是否启用 Open Graph
  open_graph:
    enable: true
    image: https://s2.loli.net/2025/12/22/nBapAxK8NowjZFP.png  # 默认 og:image
    description: 这是一个很无趣的人写的很无趣的文章
  # Google Analytics（谷歌统计）
  google_analytics:
    enable: false # 是否启用 Google Analytics
    id:  # Google Analytics Measurement ID（衡量 ID）
# 站点自定义 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束
    

# Font Awesome >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/basic/fontawesome
fontawesome: # Pro 版 v6.2.1
  # Thin 版本
  thin: false
  # Light 版本
  light: false
  # Duotone 版本
  duotone: false
  # Sharp Solid 版本
  sharp_solid: false
# Font Awesome <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 首页横幅 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/home/home_banner
home_banner:
  # 是否启用首页横幅
  enable: true
  # 首页横幅样式
  style: fixed # static（静态）/ fixed（固定）
  # 首页横幅图片
  image: 
    light: https://s2.loli.net/2025/12/22/nBapAxK8NowjZFP.png # 浅色模式
    dark: https://s2.loli.net/2025/12/22/uBnZDzxcI7JHCX3.png # 深色模式
  # 首页横幅标题
  title: ALp_Studio
  # 首页横幅副标题
  subtitle:
    text: ["欢迎进入，实验体","情感数据记录中……"] # 副标题文本（数组）
    hitokoto:  # 一言配置
      enable: true # 是否启用一言
      show_author: true # 是否显示作者
      api: https://v1.hitokoto.cn # API URL，可追加 types 参数，见 https://developer.hitokoto.cn/sentence/#%E5%8F%A5%E5%AD%90%E7%B1%BB%E5%9E%8B-%E5%8F%82%E6%95%B0
    typing_speed: 100 # 打字速度（ms）
    backing_speed: 80 # 回退速度（ms）
    starting_delay: 500 # 开始延迟（ms）
    backing_delay: 1500 # 回退延迟（ms）
    loop: true # 是否循环
    smart_backspace: true # 是否启用智能回退
  # 首页横幅文字颜色
  text_color: 
    light: "#000000" # 浅色模式
    dark: "#d1d1b6" # 深色模式
  # 文字细节样式
  text_style: 
    # 标题字号
    title_size: 2.8rem
    # 副标题字号
    subtitle_size: 1.5rem
    # 标题与副标题行高
    line_height: 1.2
  # 首页横幅自定义字体
  custom_font: 
    # 是否启用自定义字体
    enable: false
    # 字体族
    family: 
    # 字体 CSS 文件 URL
    url:
  # 首页横幅社交链接
  social_links:
    # 是否启用
    enable: true
    # 社交链接样式
    style: default # default（默认）, reverse（反转）, center（居中）
    # 链接列表
    links:
      github: https://github.com/RE-TikaRa
      bilibili: https://space.bilibili.com/374412219
      email: 163mail@re-tikara.fun # 你的邮箱
      # ...... # 你可以继续添加更多
    # 带二维码抽屉的社交链接
    qrs:
      weixin:  # 你的微信二维码图片 URL
      # ...... # 你可以继续添加更多
# 首页横幅 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 导航栏 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/home/navbar
navbar:
  # 自动隐藏导航栏
  auto_hide: true
  # 导航栏背景色
  color:
    left: "#f78736" # 左侧
    right: "#367df7"  # 右侧
    transparency: 35 # 透明度百分比（10-99）
  # 导航栏宽度（一般无需修改）
  width:
    home: 1200px # 首页
    pages: 1000px # 其他页面
  # 导航栏链接
  links:
    Home: 
      path: / 
      icon: fa-regular fa-house # 可留空
    Tag:
      path: /tags/ 
      icon: fa-solid fa-tags
    Categories: 
      icon: fa-solid fa-folder #图标
      path: /categories/ #链接
    Bookmarks: #取名随意
      icon: fa-solid fa-bookmark #图标
      path: /bookmarks/
    # Status: 
    #   path: https://status.ohevan.com/
    #   icon: fa-regular fa-chart-bar
    About: 
      icon: fa-regular fa-user
      submenus:
        Me: /about
        Github: https://github.com/RE-TikaRa
        BiliBili: https://space.bilibili.com/374412219
        相册: /masonry
        Archives: /archives
        Friends: /links
        Bookmarks: /bookmarks
    #     Blog: https://ohevan.com
    #     Friends: /friends
    # Links: 
    #   icon: fa-regular fa-link
    #   submenus:
    #     Link1: /link1
    #     Link2: /link2
    #     Link3: /link3
    # ...... # 你可以继续添加更多
  # 导航栏搜索（本地搜索）。需要 hexo-generator-searchdb（npm i hexo-generator-searchdb）。见 https://github.com/theme-next/hexo-generator-searchdb
  search:
    # 是否启用
    enable: true
    # 页面加载时预加载搜索数据
    preload: true
# 导航栏 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 首页文章设置 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/home/home
home:
  # 侧边栏设置
  sidebar:
    enable: true # 是否启用侧边栏
    position: left # 侧边栏位置。left（左）, right（右）
    first_item: menu # 侧边栏第一项。menu, info
    announcement: # 公告文本
    show_on_mobile: true # 是否在移动端抽屉菜单中显示侧边栏导航
    links:
        MainWeb: 
          path: https://re-tikara.fun
          icon: fa-solid fa-globe
        Archives: 
          path: /archives 
          icon: fa-regular fa-archive # 可留空
        Tags: 
          path: /tags 
          icon: fa-regular fa-tags # 可留空
        Categories: 
          path: /categories 
          icon: fa-regular fa-folder # 可留空
      # ...... # 你可以继续添加更多
  # 文章日期格式
  article_date_format: auto # auto, relative, YYYY-MM-DD, YYYY-MM-DD HH:mm:ss 等
  # 文章摘要长度
  excerpt_length: 200 # 文章摘要最大长度
  # 文章分类显示
  categories:
    enable: true  # 是否启用
    limit: 3 # 最多显示分类数
  # 文章标签显示
  tags:
    enable: true  # 是否启用
    limit: 3  # 最多显示标签数
# 首页文章设置 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 文章 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/posts/articles
articles:
  # 文章样式设置
  style:
    font_size: 16px # 字号
    line_height: 1.5 # 行高
    image_border_radius: 14px # 图片圆角
    image_alignment: center # 图片对齐方式。left, center
    image_caption: false # 是否显示图片说明
    link_icon: true # 是否显示链接图标
    delete_mask: false # 为 <del> 添加遮罩效果：默认隐藏，悬停显示
    title_alignment: left # 标题对齐方式。left, center
    headings_top_spacing: # h1-h6 标题的顶部间距
      h1: 3.2rem
      h2: 2.4rem
      h3: 1.9rem
      h4: 1.6rem
      h5: 1.4rem
      h6: 1.3rem
  # 字数统计。需要 hexo-wordcount（npm install hexo-wordcount）。见 https://github.com/willin/hexo-wordcount
  word_count:
    enable: true # 是否启用
    count: true # 是否显示字数
    min2read: true # 是否显示阅读时长
  # 作者标签
  author_label: 
    enable: true # 是否启用
    auto: false # 是否自动添加作者标签，例如 Lv1、Lv2、Lv3...
    list: []
  # 代码块设置
  code_block:
    copy: true # 是否启用复制按钮
    style: mac # mac | simple
    highlight_theme: # highlight.js 代码高亮配色；预览见 https://highlightjs.org/examples
      light: github # 浅色模式主题：github、atom-one-light、default
      dark: vs2015 # 深色模式主题：github-dark、monokai-sublime、vs2015、night-owl、atom-one-dark、nord、tokyo-night-dark、a11y-dark、agate
    font: # 自定义字体
      enable: false # 是否启用
      family: # 字体族
      url: # 字体 CSS 文件 URL
  # 目录（TOC）设置
  toc:
    enable: true # 是否启用 TOC
    max_depth: 3 # TOC 深度
    number: false # 是否自动为 TOC 添加编号
    expand: true # 是否展开 TOC
    init_open: true # 默认展开 TOC
  # 是否启用版权声明
  copyright:
    enable: true # 是否启用
    default: cc_by_nc_sa # 默认协议：cc_by_nc_sa, cc_by_nd, cc_by_nc, cc_by_sa, cc_by, all_rights_reserved, public_domain
  # 是否对图片启用懒加载
  lazyload: true
  # Pangu.js（自动在中英文之间添加空格）。见 https://github.com/vinta/pangu.js
  pangu_js: false
  # 文章推荐。需要 nodejieba（npm install nodejieba），移植自 hexo-theme-volantis。
  recommendation:
    # 是否启用文章推荐
    enable: false
    # 文章推荐标题
    title: 推荐阅读
    # 最多显示文章数
    limit: 3
    # 移动端最多显示文章数
    mobile_limit: 2
    # 占位图
    placeholder: /images/wallhaven-wqery6-light.webp
    # 跳过目录
    skip_dirs: []
# 文章 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 评论 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/posts/comment
comment:
  # 是否启用评论
  enable: flase
  # 评论系统
  system: gitalk # waline, gitalk, twikoo, giscus
  # 系统配置
  config:
    # Waline 评论系统。见 https://waline.js.org/
    waline:
      serverUrl: https://example.example.com # Waline 服务端地址，例如 https://example.example.com
      lang: zh-CN # Waline 语言，例如 zh-CN、en-US。见 https://waline.js.org/guide/client/i18n.html
      emoji: [] # Waline 表情，见 https://waline.js.org/guide/features/emoji.html
      recaptchaV3Key: # Google reCAPTCHA v3 key。见 https://waline.js.org/reference/client/props.html#recaptchav3key
      turnstileKey: # Turnstile key。见 https://waline.js.org/reference/client/props.html#turnstilekey
      reaction: false # Waline 反应（Reaction）。见 https://waline.js.org/reference/client/props.html#reaction
    # Gitalk 评论系统。见 https://github.com/gitalk/gitalk
    gitalk:
      clientID: # GitHub 应用 Client ID
      clientSecret: # GitHub 应用 Client Secret
      repo: # GitHub 仓库名
      owner: # GitHub 仓库所有者
      proxy:  # GitHub 仓库代理
    # Twikoo 评论系统。见 https://twikoo.js.org/
    twikoo:
      version: 1.6.10 # Twikoo 版本；不清楚用途时请勿修改
      server_url: # Twikoo 服务端地址，例如 https://example.example.com
      region: # Twikoo 区域；可留空
    # Giscus 评论系统。见 https://giscus.app/
    giscus:
      repo: # GitHub 仓库名，例如 EvanNotFound/hexo-theme-redefine
      repo_id: # GitHub 仓库 ID
      category: # GitHub Discussion 分类
      category_id: # GitHub Discussion 分类 ID
      mapping: pathname # 页面唯一标识使用的字段，例如 pathname、url、title、og:title；启用 PJAX 时不要用 og:title，因为切页时 pjax 不会更新 og:title
      strict: 0 # 是否启用严格模式，例如 0、1
      reactions_enabled: 1 # 是否启用反应（Reactions），例如 0、1
      emit_metadata: 0 # 是否输出元数据（metadata），例如 0、1
      lang: en # Giscus 语言，例如 en、zh-CN、zh-TW
      input_position: bottom # 评论框位置（在评论上方/下方），例如 top、bottom
      loading: lazy # 懒加载评论
# 评论 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 页脚 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/footer
footer:
  # 显示站点运行时间
  runtime: true # 是否显示站点运行时间
  # 页脚图标：在这里填写 Font Awesome 图标 HTML
  icon: '<i class="fa-solid fa-heart fa-beat" style="--fa-animation-duration: 0.5s; color: #f54545"></i>'
  # 站点开始时间，格式：YYYY/MM/DD HH:mm:ss
  start: 2023-12-16 14:23:50
  # 站点统计
  statistics: true # 是否显示站点统计（文章总数、总字数）
  # 页脚文案
  customize: 非常感谢你能坚持到这里！
  # ICP 备案号。见 https://beian.miit.gov.cn/
  icp:
    enable: false # 是否启用
    number: # ICP 备案号
    url: # ICP 备案链接
# 页脚 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 注入 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/inject
inject:
  # 是否启用注入
  enable: false
  # 注入自定义 head HTML
  head: 
    -
    -
  # 注入自定义 footer HTML
  footer:
    -
    -
# 注入 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 插件 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/plugins
plugins:
  # RSS 订阅。需要 hexo-generator-feed（npm i hexo-generator-feed）。见 https://github.com/hexojs/hexo-generator-feed
  feed:
    enable: false # 是否启用
  # APlayer。见 https://github.com/DIYgod/APlayer
  aplayer:
    enable: false # 是否启用
    type: fixed # fixed（固定）, mini（迷你）
    audios:
      - name: # 音频名称
        artist: # 音频作者/歌手
        url: # 音频 URL
        cover: # 封面 URL
        lrc: # 歌词（LRC）URL
#      - name: # 音频名称
#        artist: # 音频作者/歌手
#        url: # 音频 URL
#        cover: # 封面 URL
#        lrc: # 歌词（LRC）URL
      # .... 你可以在这里继续添加更多音频
  # Mermaid。需要 hexo-filter-mermaid-diagrams（npm i hexo-filter-mermaid-diagrams）。见 https://mermaid.js.org/
  mermaid:
    enable: false # 是否启用 Mermaid
    version: "11.4.1" # 默认 v11.4.1
# 插件 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 页面模板 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/page_templates
page_templates:
  # 友情链接页列数
  friends_column: 2
  # 标签页样式
  tags_style: blur # blur, cloud
# 页面模板 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# CDN >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/cdn
cdn:
  # 是否启用 CDN
  enable: false
  # CDN 提供商
  provider: npmmirror # npmmirror, zstatic, cdnjs, jsdelivr, unpkg, custom
  # 自定义 CDN URL
  # 格式示例：https://cdn.custom.com/hexo-theme-redefine/${version}/source/${path}
  # ${path} 必须指向主题的 "source" 目录根路径
  custom_url: 
# CDN <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束

# 开发者模式 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/developer
developer:
  # 是否启用开发者模式（仅适用于需要修改主题源码的开发者，普通用户不建议开启）
  enable: false
# 开发者模式 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束
